# Site settings
title: Home
email: josep@ctbs.me
baseurl: "/home" # the subpath of your site, e.g. /blog/
url: "http://www.ctbs.me/" # the base hostname & protocol for your site
twitter_username: josepctbs
github_username:  josepcasas


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
destination: _site
keep_files: [files]


gps: barcelona
music: Joe Hisaishi Meets Kitano
book: ethics by Aristotle
work: finding a job/internship
goals: 1%


