# Site settings
title: Home
email: josep@ctbs.me
baseurl: "/home" # the subpath of your site, e.g. /blog/
url: "http://www.ctbs.me/" # the base hostname & protocol for your site
twitter_username: josepctbs
github_username:  josepcasas


# Build settings
markdown: kramdown
source: 
destination: _site
keep_files: [files]


gps: Barcelona
music: Papa Topo
book: La Edad de Oro
work: Interviews