# Site settings
title: Home
email: josep@ctbs.me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ctbs.me/home" # the base hostname & protocol for your site
twitter_username: josepctbs
github_username:  josepcasas


# Build settings
markdown: kramdown
source: ./_app
destination: ./_site
keep_files: [files]


gps: Barcelona
music: Papa Topo
book: La Edad de Oro by José Martí
work: Interviews