# Site settings
title: Home
email: josep@ctbs.me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ctbs.me" # the base hostname & protocol for your site
twitter_username: josepctbs
github_username:  josepcasas


# Build settings
markdown: kramdown
source: ./_app
destination: /html


gps: Barcelona
music: Sabina
book: Meditations by Marcus Aurelius
work: Interviews